#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2026 Samuele Voltan
#
# LBA2 Nintendo 64 build driver (libdragon).
#
# Run it from this directory on the host: when the libdragon toolchain is not
# on the machine (no $N64_INST), the script re-executes itself inside the
# n64lba-toolchain Docker image (built on first use from docker/Dockerfile.n64,
# on top of the official ghcr.io/dragonminded/libdragon toolchain image).
# Inside the container it generates the files CMake produces on the other
# platforms, stages the game data into the DFS (bring your own assets: the
# retail files come from a local directory, never from the repo) and runs make.
#
# Usage:
#   ./build-n64.sh [-jN]        # build lba2.z64 (+ lba2.dfs staging)
#   ./build-n64.sh clean        # rm -rf build-n64/ lba2.z64
#   ./build-n64.sh shell        # interactive shell inside the container
#
# Environment overrides:
#   DOCKER    - docker binary (default: docker on PATH)
#   IMAGE     - Docker image tag (default: n64lba-toolchain:latest)
#   GAMEDATA  - directory with the retail LBA2 data (*.HQR, *.ILE, *.OBL,
#               music/, vox/); default: ../../CommonGOG
#   N64_AUDIO_DIAG - 1 = audio diagnostics ROM (boot self-test + HUD)
set -e

GAMEDATA="${GAMEDATA:-../../CommonGOG}"

case "${1:-}" in
    clean)
        rm -rf build-n64 lba2.z64 lba2.dfs
        echo "Cleaned build-n64/"
        exit 0
        ;;
esac

if [ -z "$N64_INST" ]; then
    # --- host side: hand over to the toolchain container -------------------
    DOCKER="${DOCKER:-docker}"
    IMAGE="${IMAGE:-n64lba-toolchain:latest}"
    export MSYS_NO_PATHCONV=1
    if ! "$DOCKER" image inspect "$IMAGE" >/dev/null 2>&1; then
        echo "[build-n64] building toolchain image $IMAGE (one-off, a few minutes)"
        "$DOCKER" build -t "$IMAGE" -f docker/Dockerfile.n64 docker
    fi
    # Mount the parent of the parent so the default ../../CommonGOG resolves;
    # a GAMEDATA outside that tree is mounted separately at /gamedata.
    HERE="$(cd "$(pwd)" && pwd)"
    ROOT="$(cd "$HERE/../.." && pwd)"
    REL="${HERE#$ROOT/}"
    EXTRA=""
    if [ -d "$GAMEDATA" ]; then
        GD="$(cd "$GAMEDATA" && pwd)"
        case "$GD" in
            "$ROOT"/*) GAMEDATA_IN="/project/${GD#$ROOT/}" ;;
            *) EXTRA="-v $GD:/gamedata"; GAMEDATA_IN="/gamedata" ;;
        esac
    else
        GAMEDATA_IN="$GAMEDATA"
    fi
    if [ "${1:-}" = "shell" ]; then
        exec "$DOCKER" run --rm -it -v "$ROOT:/project" $EXTRA -w "/project/$REL" -e "GAMEDATA=$GAMEDATA_IN" "$IMAGE" sh
    fi
    exec "$DOCKER" run --rm -v "$ROOT:/project" $EXTRA -w "/project/$REL" -e "GAMEDATA=$GAMEDATA_IN" -e "N64_AUDIO_DIAG=${N64_AUDIO_DIAG:-0}" "$IMAGE" sh build-n64.sh "$@"
fi

# --- container side -------------------------------------------------------

GEN=build-n64/generated
mkdir -p "$GEN"

# --- VERSION_GENERATED.h + BUILD_INFO.h (replaces cmake/write_version.cmake) ---
VERSION=$(cat VERSION | tr -d '\r\n')
printf '/* Generated by build-n64.sh - do not edit. */\n#define LBA2_VERSION_STRING "%s-n64"\n' "$VERSION" > "$GEN/VERSION_GENERATED.h.new"
printf '/* Generated by build-n64.sh - do not edit */\n#define BUILD_FLAGS_STR "n64-libdragon"\n#include "VERSION_GENERATED.h"\n' > "$GEN/BUILD_INFO.h.new"

# --- embedded LBA2.CFG (replaces cmake/embed_lba2_cfg.cmake) ---
{
    echo '// Generated by build-n64.sh - do not edit'
    echo '#include <SYSTEM/ADELINE_TYPES.H>'
    echo ''
    echo 'extern "C" const unsigned char g_embeddedLba2CfgBytes[] = {'
    od -An -v -tx1 SOURCES/LBA2.CFG | awk '{for(i=1;i<=NF;i++) printf "0x%s,", $i; print ""}'
    echo '};'
    echo ''
    echo 'extern "C" const U32 g_embeddedLba2CfgBytesSize = (U32)sizeof(g_embeddedLba2CfgBytes);'
} > "$GEN/embedded_lba2_cfg_data.cpp.new"

# Only touch outputs when content changed (keeps make from rebuilding every run)
for f in VERSION_GENERATED.h BUILD_INFO.h embedded_lba2_cfg_data.cpp; do
    if ! cmp -s "$GEN/$f.new" "$GEN/$f" 2>/dev/null; then
        mv "$GEN/$f.new" "$GEN/$f"
    else
        rm "$GEN/$f.new"
    fi
done

# --- DFS staging: BYOA — assets come from the local retail copy ($GAMEDATA), never
# from the repo. DFS is case-sensitive and the engine composes lowercase
# names (ress.hqr, samples.hqr...), so stage everything lowercase at the DFS
# root: discovery then resolves the resource dir to plain "rom:/".
DFSROOT=build-n64/dfsroot
rm -rf "$DFSROOT/data" # layout of an earlier iteration
mkdir -p "$DFSROOT"
# Hardware triage build: N64_AUDIO_DIAG=1 stages the marker file that wakes
# the audio diagnostics (boot PI read self-test + in-game HUD, see
# LIB386/SYSTEM/N64_AUDIODIAG.CPP). Same code either way; only the marker.
if [ "${N64_AUDIO_DIAG:-0}" = "1" ]; then
    echo "audio diagnostics" > "$DFSROOT/audiodiag"
    echo "[build-n64] AUDIO DIAGNOSTICS BUILD (rom:/audiodiag staged)"
elif [ -f "$DFSROOT/audiodiag" ]; then
    # make does not notice a file leaving the DFS: force the image rebuild.
    rm -f "$DFSROOT/audiodiag" build-n64/lba2.dfs
fi
if [ -d "$GAMEDATA" ]; then
    find "$GAMEDATA" -maxdepth 1 -type f | while read -r f; do
        base=$(basename "$f" | tr 'A-Z' 'a-z')
        cp -u "$f" "$DFSROOT/$base"
    done
    # The engine's user/cfg dir is cartridge SRAM ("sram:/", see
    # LIB386/SYSTEM/N64_SRAMFS.CPP): saves and lba2.cfg live there. On a blank
    # SRAM the engine copies the default cfg from the resource dir, so stage
    # it at the DFS root with the N64 defaults (English text; the stock file
    # is Adeline's French dev config).
    # Developer overrides (DebugStartCube, DebugSaveTest...) go in
    # build-n64/lba2.cfg.local, appended to the staged file. Mind that the
    # engine copies the cfg into SRAM on first boot only: delete the
    # emulator's .ram/.sav to see a changed default again.
    rm -rf "$DFSROOT/saves" # layout of the read-only V1 (rom:/saves/)
    {
        sed 's/^Language: .*/Language: English/' SOURCES/LBA2.CFG
        if [ -f build-n64/lba2.cfg.local ]; then echo; cat build-n64/lba2.cfg.local; fi
    } > "$DFSROOT/lba2.cfg.new"
    if ! cmp -s "$DFSROOT/lba2.cfg.new" "$DFSROOT/lba2.cfg" 2>/dev/null; then
        mv "$DFSROOT/lba2.cfg.new" "$DFSROOT/lba2.cfg"
    else
        rm -f "$DFSROOT/lba2.cfg.new"
    fi
    # --- Music: GOG .ogg -> .wav64 (VADPCM, decoded on the RSP by the libdragon
    # mixer). We used Opus (--wav-compress 3) before, but Opus decodes on the
    # VR4300 CPU — heavy enough to drop the frame rate and crackle during
    # playback. VADPCM is RSP-accelerated (CPU stays free -> 60 fps), at the
    # cost of a much lower compression ratio; downmixing to mono 22050 Hz keeps
    # the total within the ROM budget. ffmpeg decodes+resamples, audioconv64 packs.
    MUSIC_FMT="vadpcm-mono-16000"
    MUSIC_FMT_FILE="build-n64/.music_fmt" # sentinel OUTSIDE the DFS staging tree
    if [ -d "$GAMEDATA"/music ] && command -v ffmpeg >/dev/null 2>&1; then
        mkdir -p "$DFSROOT/music"
        # The per-file cache below keys off timestamps only, so a format change
        # would leave stale wav64 in place. Wipe them when the target changes.
        if [ "$(cat "$MUSIC_FMT_FILE" 2>/dev/null)" != "$MUSIC_FMT" ]; then
            rm -f "$DFSROOT/music"/*.wav64
            echo "$MUSIC_FMT" > "$MUSIC_FMT_FILE"
        fi
        for f in "$GAMEDATA"/music/*.ogg; do
            [ -f "$f" ] || continue
            base=$(basename "$f" .ogg | tr 'A-Z' 'a-z')
            out="$DFSROOT/music/$base.wav64"
            if [ ! -f "$out" ] || [ "$f" -nt "$out" ]; then
                tmp="/tmp/$base.wav"
                ffmpeg -loglevel error -y -i "$f" -ar 16000 -ac 1 "$tmp"
                "$N64_INST/bin/audioconv64" --wav-compress 1 -o "$DFSROOT/music" "$tmp"
                mv "$DFSROOT/music/$base.wav64" "$out" 2>/dev/null || true
                rm -f "$tmp"
            fi
        done
        echo "[build-n64] music: $(ls "$DFSROOT/music"/*.wav64 2>/dev/null | wc -l) wav64 ($MUSIC_FMT), $(du -sh "$DFSROOT/music" | cut -f1)"
    fi

    # --- Voices: EN_*.VOX (HQR of RIFF/IMA-ADPCM clips, ~83 MB) -> per-clip Opus
    # .wav64 (RSP-streamed on the voice channel) + tiny placeholder VOX HQRs that
    # keep the engine's voice indexing intact (see tools-n64/vox_repack.py and the
    # SPEAK_SAMPLE reroute in SOUND_N64_BACKEND.CPP). English only for now; a
    # French/German config just finds no wav64 and stays silent. Opus @12 kHz mono
    # fits ~132 min of speech in ~16 MB. Whole step is cached behind a sentinel
    # since the retail VOX never change.
    VOX_FMT="opus-12000-en-v2"  # v2: FlagNextVoc continuation parts
    VOX_FMT_FILE="build-n64/.vox_fmt"
    if [ -d "$GAMEDATA"/vox ] && command -v ffmpeg >/dev/null 2>&1; then
        if [ "$(cat "$VOX_FMT_FILE" 2>/dev/null)" != "$VOX_FMT" ] || [ ! -d "$DFSROOT/vox" ]; then
            echo "[build-n64] voices: repacking (this is slow, but cached afterwards)..."
            rm -rf "$DFSROOT/vox" build-n64/voxwav
            mkdir -p "$DFSROOT/vox" build-n64/voxwav
            python3 tools-n64/vox_repack.py "$GAMEDATA/vox" build-n64/voxwav "$DFSROOT/vox" EN
            for w in build-n64/voxwav/*.wav; do
                [ -f "$w" ] || continue
                base=$(basename "$w" .wav)
                tmp="/tmp/$base.pcm.wav"
                ffmpeg -loglevel error -y -i "$w" -ar 12000 -ac 1 "$tmp" 2>/dev/null || continue
                "$N64_INST/bin/audioconv64" --wav-compress 3 -o "$DFSROOT/vox" "$tmp" >/dev/null 2>&1 || continue
                mv "$DFSROOT/vox/$base.pcm.wav64" "$DFSROOT/vox/$base.wav64" 2>/dev/null || true
                rm -f "$tmp"
            done
            rm -rf build-n64/voxwav
            echo "$VOX_FMT" > "$VOX_FMT_FILE"
        fi
        echo "[build-n64] voices: $(ls "$DFSROOT/vox"/*.wav64 2>/dev/null | wc -l) clips + $(ls "$DFSROOT/vox"/*.vox 2>/dev/null | wc -l) VOX ($VOX_FMT), $(du -sh "$DFSROOT/vox" | cut -f1)"
    fi

    echo "[build-n64] DFS staging: $(ls "$DFSROOT" | wc -l) entries, $(du -sh "$DFSROOT" | cut -f1)"
else
    echo "[build-n64] WARNING: $GAMEDATA not found - ROM will have no assets (set GAMEDATA=/path/to/retail/data)"
fi

make -f Makefile.n64 "$@" || exit $?

# --- Toolchain sanity: the libdragon inthandler patch --------------------------
# The port emulates unaligned accesses in its address-error handler
# (LIB386/SYSTEM/N64_BACKEND.CPP), which writes the result into the saved
# register frame. Stock libdragon never reloads s0-s7 on the way out of an
# exception, so an emulated load into one of those registers is silently
# dropped and the code runs on a stale value - rare, scene-dependent, and it
# has already cost two hardware crashes. docker/Dockerfile.n64 patches
# inthandler.S; a toolchain image built before that patch produces a ROM that
# looks fine and misbehaves in the field, so refuse to ship one.
if [ -f build-n64/lba2.elf ]; then
    CRIT=$(mips64-elf-nm build-n64/lba2.elf 2>/dev/null | awk '/ [Tt] exception_critical$/ { print $1; exit }')
    if [ -n "$CRIT" ]; then
        if mips64-elf-objdump -d --start-address=$((0x$CRIT)) --stop-address=$((0x$CRIT + 64)) \
               build-n64/lba2.elf 2>/dev/null | grep -q 's7,216(sp)'; then
            echo "[build-n64] toolchain: libdragon inthandler s0-s7 reload OK"
        else
            echo "[build-n64] ERROR: this toolchain image's libdragon lacks the inthandler"
            echo "           s0-s7 reload patch - emulated unaligned loads into s0-s7 would"
            echo "           be dropped. Rebuild the image and then this ROM:"
            echo "           docker build -t n64lba-toolchain:latest -f docker/Dockerfile.n64 docker"
            exit 1
        fi
    fi
fi
